### ISSUE TITLE
Comparator'ы должны использоваться в сервисе

### ISSUE THREAD

**Issue by coursar** [zakiryanova-java/Yulmart#6]
https://github.com/zakiryanova-java/Yulmart/blob/42556853140cc1b1aea87e22db5a9a160b32bf33/src/main/java/ru/itpark/service/ProductService.java#L14-L30

**Comment by zakiryanova-java** [comment]
@coursar , прошу помочь с заданием. Список по категории/ по имени товаров не вижу, как можно дополнительно отсортировать по цене, по рейтингу, кроме как в main. Для чего нужно вносить компараторы в сервис?

**Comment by coursar** [comment]
Пользователь (ваш Main) ничего не сортирует - он только говорит как сортировать
